# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: sensor
  joint_model_group_pose: origin2
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
    - link_03__link_04
    - base_link__link_05
    - link_05__link_06
    - link_06__link_07
    - link_07__link_08
    - link_08__link_09
    - link_08__link_10
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: sensor_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link__link_05
      - link_05__link_06
      - link_06__link_07
      - link_07__link_08
      - link_08__link_09
      - link_08__link_10